export const COLUMNAS_CLIENTES_INTERNOS = [
    { id: 'id', nombre: 'ID', visible: false },
    { id: 'fecha_registro', nombre: 'Fecha de Registro', visible: true },
    { id: 'oficina', nombre: 'Oficina', visible: true },
    { id: 'ejecutivo', nombre: 'Ejecutivo', visible: true },
    { id: 'nombres_cliente_interno', nombre: 'Nombres', visible: true },
    { id: 'apellidos_cliente_interno', nombre: 'Apellidos', visible: true },
    { id: 'tipo_documento_cliente_interno', nombre: 'Tipo Documento', visible: true },
    { id: 'nro_documento_cliente_interno', nombre: 'Nro. Documento', visible: true },
    { id: 'extension_cliente_interno', nombre: 'Extensión', visible: false },
    { id: 'otra_extension_cliente_interno', nombre: 'Otra Extensión', visible: false },
    { id: 'fecha_nacimiento', nombre: 'Fecha Nacimiento', visible: false },
    { id: 'lugar_nacimiento', nombre: 'Lugar Nacimiento', visible: false },
    { id: 'nacionalidad', nombre: 'Nacionalidad', visible: false },
    { id: 'estado_civil', nombre: 'Estado Civil', visible: false },
    { id: 'profesion', nombre: 'Profesión', visible: true },
    { id: 'riesgo_profesion_actividad', nombre: 'Riesgo Profesión/Actividad', visible: false },
    { id: 'otra_actividad', nombre: 'Otra Actividad', visible:true},
    { id: 'riesgo_otra_actividad', nombre: 'Riesgo otra actividad', visible:false},
    { id: 'domicilio_persona_sucursal', nombre: 'Domicilio', visible: false },
    { id: 'riesgo_zona', nombre: 'Riesgo Zona', visible: false },
    { id: 'categoria_pep', nombre: 'PEP', visible: true },
    { id: 'ingresos_mensuales', nombre: 'Ingresos Mensuales', visible: false },
    { id: 'volumen_actividad', nombre: 'Volumen Actividad', visible: false },
    { id: 'frecuencia_actividad', nombre: 'Frecuencia Actividad', visible: false },
    { id: 'integridad_documental', nombre: 'Integridad Documental', visible: false },
    { id: 'exactitud_documental', nombre: 'Exactitud Documental', visible: false },
    { id: 'vigencia_documental', nombre: 'Vigencia Documental', visible: false },
    { id: 'relevancia_informacion', nombre: 'Relevancia Información', visible: false },
    { id: 'consistencia_informacion', nombre: 'Consistencia Información', visible: false },
    { id: 'comportamiento_cliente', nombre: 'Comportamiento Cliente', visible: false },
    { id: 'observaciones', nombre: 'Observaciones', visible: false },
    { id: 'alertas_cliente_interno', nombre: 'Alertas de Cliente Interno', visible: false },
    { id: 'alertas_activos_virtuales', nombre: 'Alertas de Activos Virtuales', visible: false },
    { id: 'nacionalidad_numerico', nombre: 'Nacionalidad (Ponderado)', visible: false },
    { id: 'riesgo_profesion_actividad_numerico', nombre: 'Riesgo Profesión (Ponderado)', visible: false },
    { id: 'otra_actividad_numerico', nombre: 'Riesgo Otra Actividad (Ponderado)', visible: false},
    { id: 'riesgo_zona_numerico', nombre: 'Riesgo Zona (Ponderado)', visible: false },
    { id: 'categoria_pep_numerico', nombre: 'PEP (Ponderado)', visible: false },
    { id: 'ingresos_mensuales_numerico', nombre: 'Ingresos Mensuales (Ponderado)', visible: false },
    { id: 'volumen_actividad_numerico', nombre: 'Volumen Actividad (Ponderado)', visible: false },
    { id: 'frecuencia_actividad_numerico', nombre: 'Frecuencia Actividad (Ponderado)', visible: false },
    { id: 'integridad_documental_numerico', nombre: 'Integridad Documental (Ponderado)', visible: false },
    { id: 'exactitud_documental_numerico', nombre: 'Exactitud Documental (Ponderado)', visible: false },
    { id: 'vigencia_documental_numerico', nombre: 'Vigencia Documental (Ponderado)', visible: false },
    { id: 'relevancia_informacion_numerico', nombre: 'Relevancia Información (Ponderado)', visible: false },
    { id: 'consistencia_informacion_numerico', nombre: 'Consistencia Información (Ponderado)', visible: false },
    { id: 'comportamiento_cliente_numerico', nombre: 'Comportamiento Cliente (Ponderado)', visible: false },
    { id: 'probabilidad', nombre: 'Probabilidad', visible: false },
    { id: 'impacto', nombre: 'Impacto', visible: false },
    { id: 'riesgo_inherente', nombre: 'Riesgo Inherente', visible: false },
    { id: 'mitigacion', nombre: 'Mitigación', visible: false },
    { id: 'mitigacion_numerico', nombre: 'Mitigación Relativa', visible: false },
    { id: 'mitigacion_adicional', nombre: 'Detalle de la Mitigación', visible: false },
    { id: 'riesgo_residual', nombre: 'Riesgo Residual', visible: true },
];

export const DEFAULT_COLUMNAS_CLIENTES = COLUMNAS_CLIENTES_INTERNOS.filter(col => col.visible);