export const TODAS_LAS_COLUMNAS = [
    { id: 'id', nombre: 'ID', visible: false },
    { id: 'fecha_registro', nombre: 'Fecha de Registro', visible: false },
    { id: 'oficina', nombre: 'Oficina', visible: false },
    { id: 'ejecutivo', nombre: 'Ejecutivo', visible: false },
    { id: 'tipo_sociedad', nombre: 'Tipo de Sociedad', visible: false },
    { id: 'nombres_propietario', nombre: 'Nombres Propietario', visible: true },
    { id: 'apellidos_propietario', nombre: 'Apellidos Propietario', visible: true },
    { id: 'tipo_documento_propietario', nombre: 'Tipo Documento Propietario', visible: false },
    { id: 'nro_documento_propietario', nombre: 'Nro. Documento Propietario', visible: true },
    { id: 'extension_propietario', nombre: 'Extensión Propietario', visible: false },
    { id: 'otra_extension_propietario', nombre: 'Otra Extensión Propietario', visible: false },
    { id: 'fecha_nacimiento', nombre: 'Fecha de Nacimiento', visible: false },
    { id: 'lugar_nacimiento', nombre: 'Lugar de Nacimiento', visible: false },
    { id: 'nacionalidad', nombre: 'Nacionalidad', visible: false },
    { id: 'pais_residencia', nombre: 'País de Residencia', visible: false },
    { id: 'estado_civil', nombre: 'Estado Civil', visible: false },
    { id: 'telefono', nombre: 'Teléfono', visible: true },
    { id: 'celular', nombre: 'Celular', visible: false },
    { id: 'profesion', nombre: 'Profesión', visible: false },
    { id: 'razon_social', nombre: 'Razón Social', visible: true },
    { id: 'nit', nombre: 'NIT', visible: false },
    { id: 'matricula_comercio', nombre: 'Matrícula de Comercio', visible: false },
    { id: 'actividad', nombre: 'Actividad', visible: false },
    { id: 'riesgo_profesion_actividad', nombre: 'Riesgo Profesión/Actividad', visible: false },
    { id: 'lugar_trabajo', nombre: 'Lugar de Trabajo', visible: false },
    { id: 'cargo', nombre: 'Cargo', visible: false },
    { id: 'gestion_ingreso', nombre: 'Gestión de Ingreso', visible: false },
    { id: 'riesgo_zona', nombre: 'Riesgo de Zona', visible: false },
    { id: 'ingresos_mensuales', nombre: 'Ingresos Mensuales', visible: false },
    { id: 'volumen_actividad', nombre: 'Volumen de Actividad', visible: false },
    { id: 'frecuencia_actividad', nombre: 'Frecuencia de Actividad', visible: false },
    { id: 'categoria_pep', nombre: 'Categoría PEP', visible: false },
    { id: 'domicilio_persona_sucursal', nombre: 'Domicilio Persona/Sucursal', visible: false },
    { id: 'domicilio_comercial_legal', nombre: 'Domicilio Comercial/Legal', visible: false },
    { id: 'correo', nombre: 'Correo', visible: true },
    { id: 'nombres_conyugue', nombre: 'Nombres Conyugue', visible: false },
    { id: 'apellidos_conyugue', nombre: 'Apellidos Conyugue', visible: false },
    { id: 'actividad_conyugue', nombre: 'Actividad Conyugue', visible: false },
    { id: 'ocupacion_conyugue', nombre: 'Ocupación Conyugue', visible: false },
    { id: 'nombres_representante', nombre: 'Nombres Representante', visible: false },
    { id: 'apellidos_representante', nombre: 'Apellidos Representante', visible: false },
    { id: 'tipo_documento_representante', nombre: 'Tipo Documento Representante', visible: false },
    { id: 'nro_documento_representante', nombre: 'Nro. Documento Representante', visible: false },
    { id: 'extension_representante', nombre: 'Extensión Representante', visible: false },
    { id: 'otra_extension_representante', nombre: 'Otra Extensión Representante', visible: false },
    { id: 'ramo_seguro', nombre: 'Ramo de Seguro', visible: false },
    { id: 'tipo_documento', nombre: 'Tipo de Documento', visible: false },
    { id: 'fecha_inicio', nombre: 'Fecha de Inicio', visible: false },
    { id: 'fecha_fin', nombre: 'Fecha de Fin', visible: false },
    { id: 'nro_poliza', nombre: 'Nro. de Póliza', visible: false },
    { id: 'valor_prima_dolares', nombre: 'Valor Prima (USD)', visible: false },
    { id: 'frecuencia_contacto_fisico', nombre: 'Frecuencia Contacto Físico', visible: false },
    { id: 'frecuencia_contacto_digital', nombre: 'Frecuencia Contacto Digital', visible: false },
    { id: 'medio_comunicacion', nombre: 'Medio de Comunicación', visible: false },
    { id: 'medio_pago', nombre: 'Medio de Pago', visible: false },
    { id: 'integridad_documental', nombre: 'Integridad Documental', visible: false },
    { id: 'exactitud_documental', nombre: 'Exactitud Documental', visible: false },
    { id: 'vigencia_documental', nombre: 'Vigencia Documental', visible: false },
    { id: 'relevancia_informacion', nombre: 'Relevancia de Información', visible: false },
    { id: 'consistencia_informacion', nombre: 'Consistencia de Información', visible: false },
    { id: 'comportamiento_cliente', nombre: 'Comportamiento Cliente', visible: false },
    { id: 'observaciones', nombre: 'Observaciones', visible: false },
    { id: 'autorizado_por_alta_gerencia', nombre: 'Autorización por Alta Gerencia', visible: false },
    { id: 'alertas_vinculacion', nombre: 'Alertas de Vinculación', visible: false },
    /*{ id: 'alertas_pago_prima', nombre: 'Alertas de Pago Prima', visible: false },*/
    { id: 'alertas_emision_renovacion', nombre: 'Alertas de emisión renovación', visible: false },
    { id: 'alertas_rescision', nombre: 'Alertas de Rescisión', visible: false },
    { id: 'alertas_activos_virtuales', nombre: 'Alertas de Activos Virtuales', visible: false },
    { id: 'nacionalidad_numerico', nombre: 'Riesgo País (Ponderado)', visible: false },
    { id: 'riesgo_profesion_actividad_numerico', nombre: 'Riesgo Profesión/Actividad (Ponderado)', visible: false },
    { id: 'riesgo_zona_numerico', nombre: 'Riesgo Zona (Ponderado)', visible: false },
    { id: 'ingresos_mensuales_numerico', nombre: 'Riesgo Ingresos (Ponderado)', visible: false },
    { id: 'volumen_actividad_numerico', nombre: 'Riesgo Volumen Actividad (Ponderado)', visible: false },
    { id: 'frecuencia_actividad_numerico', nombre: 'Riesgo Frecuencia Actividad (Ponderado)', visible: false },
    { id: 'categoria_pep_numerico', nombre: 'Riesgo Categoría PEP (Ponderado)', visible: false },
    { id: 'ramo_seguro_numerico', nombre: 'Riesgo Ramo Seguro (Ponderado)', visible: false },
    { id: 'tipo_documento_numerico', nombre: 'Riesgo Tipo Documento (Ponderado)', visible: false },
    { id: 'valor_prima_dolares_numerico', nombre: 'Riesgo Valor Prima (Ponderado)', visible: false },
    { id: 'frecuencia_contacto_fisico_numerico', nombre: 'Riesgo Contacto Físico (Ponderado)', visible: false },
    { id: 'frecuencia_contacto_digital_numerico', nombre: 'Riesgo Contacto Digital (Ponderado)', visible: false },
    { id: 'medio_comunicacion_numerico', nombre: 'Riesgo Medio Comunicación (Ponderado)', visible: false },
    { id: 'medio_pago_numerico', nombre: 'Riesgo Medio Pago (Ponderado)', visible: false },
    { id: 'integridad_documental_numerico', nombre: 'Riesgo Integridad Documental (Ponderado)', visible: false },
    { id: 'exactitud_documental_numerico', nombre: 'Riesgo Exactitud Documental (Ponderado)', visible: false },
    { id: 'vigencia_documental_numerico', nombre: 'Riesgo Vigencia Documental (Ponderado)', visible: false },
    { id: 'relevancia_informacion_numerico', nombre: 'Riesgo Relevancia Información (Ponderado)', visible: false },
    { id: 'consistencia_informacion_numerico', nombre: 'Riesgo Consistencia Información (Ponderado)', visible: false },
    { id: 'probabilidad_canal_distribucion', nombre: 'Probabilidad del Canal de Distribución', visible: false },
    { id: 'impacto_canal_distribucion', nombre: 'Impacto del Canal de distribución', visible: false },
    { id: 'promedio_riesgo_canal_distribucion', nombre: 'Riesgo Promedio Canal de Distribución', visible: false },
    { id: 'probabilidad_cliente_externo', nombre: 'Probabilidad del Cliente Externo', visible: false },
    { id: 'impacto_cliente_externo', nombre: 'Impacto del Cliente Externo', visible: false },
    { id: 'promedio_riesgo_cliente_externo', nombre: 'Riesgo Promedio Cliente Externo', visible: false },
];
export const DEFAULT_VISIBLE_COLUMNS = TODAS_LAS_COLUMNAS.filter(col => col.visible);