export const COLUMNAS_ACCIONISTAS_SOCIOS = [
    { id: 'id', nombre: 'ID', visible: false },
    { id: 'fecha_registro', nombre: 'Fecha de Registro', visible: true },
    { id: 'oficina', nombre: 'Oficina', visible: false },
    { id: 'ejecutivo', nombre: 'Ejecutivo', visible: false },
    { id: 'nombres_accionistas_socios', nombre: 'Nombres', visible: true },
    { id: 'apellidos_accionistas_socios', nombre: 'Apellidos', visible: true },
    { id: 'tipo_documento_accionistas_socios', nombre: 'Tipo Documento', visible: true },
    { id: 'nro_documento_accionistas_socios', nombre: 'Nro. Documento', visible: true },
    { id: 'extension_accionistas_socios', nombre: 'Extensión', visible: false },
    { id: 'otra_extension_accionistas_socios', nombre: 'Otra Extensión', visible: false },
    { id: 'fecha_nacimiento', nombre: 'Fecha Nacimiento', visible: false },
    { id: 'lugar_nacimiento', nombre: 'Lugar Nacimiento', visible: false },
    { id: 'nacionalidad', nombre: 'Nacionalidad', visible: false },
    { id: 'estado_civil', nombre: 'Estado Civil', visible: false },
    { id: 'domicilio_persona', nombre: 'Domicilio', visible: false },
    { id: 'actividad', nombre: 'Actividad', visible: false },
    { id: 'riesgo_actividad', nombre: 'Riesgo Actividad', visible: false },
    { id: 'riesgo_zona', nombre: 'Riesgo Zona', visible: false },
    { id: 'categoria_pep', nombre: 'PEP', visible: true },
    { id: 'ingresos_mensuales', nombre: 'Ingresos Mensuales', visible: false },
    { id: 'volumen_actividad', nombre: 'Volumen Actividad', visible: false },
    { id: 'frecuencia_actividad', nombre: 'Frecuencia Actividad', visible: false },
    { id: 'participacion_accionaria', nombre: 'Participación', visible: true },
    { id: 'integridad_documental', nombre: 'Integridad Documental', visible: false },
    { id: 'exactitud_documental', nombre: 'Exactitud Documental', visible: false },
    { id: 'vigencia_documental', nombre: 'Vigencia Documental', visible: false },
    { id: 'relevancia_informacion', nombre: 'Relevancia Información', visible: false },
    { id: 'consistencia_informacion', nombre: 'Consistencia Información', visible: false },
    { id: 'comportamiento_cliente', nombre: 'Comportamiento', visible: false },
    { id: 'observaciones', nombre: 'Observaciones', visible: false },
    { id: 'nacionalidad_numerico', nombre: 'Riesgo Nacionalidad', visible: false },
    { id: 'riesgo_actividad_numerico', nombre: 'Riesgo Actividad (Ponderado)', visible: false },
    { id: 'riesgo_zona_numerico', nombre: 'Riesgo Zona (Ponderado)', visible: false },
    { id: 'ingresos_mensuales_numerico', nombre: 'Riesgo Ingresos (Ponderado)', visible: false },
    { id: 'volumen_actividad_numerico', nombre: 'Riesgo Volumen (Ponderado)', visible: false },
    { id: 'frecuencia_actividad_numerico', nombre: 'Riesgo Frecuencia (Ponderado)', visible: false },
    { id: 'categoria_pep_numerico', nombre: 'Riesgo PEP (Ponderado)', visible: false },
    { id: 'participacion_accionaria_numerico', nombre: 'Riesgo Participación (Ponderado)', visible: false },
    { id: 'integridad_documental_numerico', nombre: 'Riesgo Integridad (Ponderado)', visible: false },
    { id: 'exactitud_documental_numerico', nombre: 'Riesgo Exactitud (Ponderado)', visible: false },
    { id: 'vigencia_documental_numerico', nombre: 'Riesgo Vigencia (Ponderado)', visible: false },
    { id: 'relevancia_informacion_numerico', nombre: 'Riesgo Relevancia (Ponderado)', visible: false },
    { id: 'consistencia_informacion_numerico', nombre: 'Riesgo Consistencia (Ponderado)', visible: false },
    { id: 'comportamiento_cliente_numerico', nombre: 'Riesgo Comportamiento (Ponderado)', visible: false },
    { id: 'probabilidad', nombre: 'Probabilidad', visible: false },
    { id: 'impacto', nombre: 'Impacto', visible: false },
    { id: 'promedio_riesgo_accionista_socio', nombre: 'Riesgo Promedio Accionista Socio', visible: false },
];

export const DEFAULT_COLUMNAS_ACCIONISTAS = COLUMNAS_ACCIONISTAS_SOCIOS.filter(col => col.visible);