export const CLIENTES_EXTERNOS_SCHEMA = {
  requiredFields: [
    'Ramo de Seguro',
    'Nro. de Póliza',
    'Valor Prima (USD)'
  ],
  fieldMappings: {
    'ID': 'id',
    'Fecha de Registro': 'fecha_registro',
    'Oficina': 'oficina',
    'Ejecutivo': 'ejecutivo',
    'Tipo de Sociedad': 'tipo_sociedad',
    'Nombres Propietario': 'nombres_propietario',
    'Apellidos Propietario': 'apellidos_propietario',
    'Tipo Documento Propietario': 'tipo_documento_propietario',
    'Nro. Documento Propietario': 'nro_documento_propietario',
    'Extensión Propietario': 'extension_propietario',
    'Otra Extensión Propietario': 'otra_extension_propietario',
    'Fecha de Nacimiento': 'fecha_nacimiento',
    'Lugar de Nacimiento': 'lugar_nacimiento',
    'Nacionalidad': 'nacionalidad',
    'País de Residencia': 'pais_residencia',
    'Estado Civil': 'estado_civil',
    'Teléfono': 'telefono',
    'Celular': 'celular',
    'Profesión': 'profesion',
    'Razón Social': 'razon_social',
    'NIT': 'nit',
    'Matrícula de Comercio': 'matricula_comercio',
    'Actividad': 'actividad',
    'Riesgo Profesión/Actividad': 'riesgo_profesion_actividad',
    'Lugar de Trabajo': 'lugar_trabajo',
    'Cargo': 'cargo',
    'Gestión de Ingreso': 'gestion_ingreso',
    'Riesgo de Zona': 'riesgo_zona',
    'Ingresos Mensuales': 'ingresos_mensuales',
    'Volumen de Actividad': 'volumen_actividad',
    'Frecuencia de Actividad': 'frecuencia_actividad',
    'Categoría PEP': 'categoria_pep',
    'Domicilio Persona/Sucursal': 'domicilio_persona_sucursal',
    'Domicilio Comercial/Legal': 'domicilio_comercial_legal',
    'Correo': 'correo',
    'Nombres Conyugue': 'nombres_conyugue',
    'Apellidos Conyugue': 'apellidos_conyugue',
    'Actividad Conyugue': 'actividad_conyugue',
    'Ocupación Conyugue': 'ocupacion_conyugue',
    'Nombres Representante': 'nombres_representante',
    'Apellidos Representante': 'apellidos_representante',
    'Tipo Documento Representante': 'tipo_documento_representante',
    'Nro. Documento Representante': 'nro_documento_representante',
    'Extensión Representante': 'extension_representante',
    'Otra Extensión Representante': 'otra_extension_representante',
    'Ramo de Seguro': 'ramo_seguro',
    'Tipo de Documento': 'tipo_documento',
    'Fecha de Inicio': 'fecha_inicio',
    'Fecha de Fin': 'fecha_fin',
    'Nro. de Póliza': 'nro_poliza',
    'Valor Prima (USD)': 'valor_prima_dolares',
    'Frecuencia Contacto Físico': 'frecuencia_contacto_fisico',
    'Frecuencia Contacto Digital': 'frecuencia_contacto_digital',
    'Medio de Comunicación': 'medio_comunicacion',
    'Medio de Pago': 'medio_pago',
    'Integridad Documental': 'integridad_documental',
    'Exactitud Documental': 'exactitud_documental',
    'Vigencia Documental': 'vigencia_documental',
    'Relevancia de Información': 'relevancia_informacion',
    'Consistencia de Información': 'consistencia_informacion',
    'Comportamiento Cliente': 'comportamiento_cliente',
    'Observaciones': 'observaciones',
    
    // Campos numéricos (ponderados)
    'Riesgo País (Ponderado)': 'nacionalidad_numerico',
    'Riesgo Profesión/Actividad (Ponderado)': 'riesgo_profesion_actividad_numerico',
    'Riesgo Zona (Ponderado)': 'riesgo_zona_numerico',
    'Riesgo Ingresos (Ponderado)': 'ingresos_mensuales_numerico',
    'Riesgo Volumen Actividad (Ponderado)': 'volumen_actividad_numerico',
    'Riesgo Frecuencia Actividad (Ponderado)': 'frecuencia_actividad_numerico',
    'Riesgo Categoría PEP (Ponderado)': 'categoria_pep_numerico',
    'Riesgo Ramo Seguro (Ponderado)': 'ramo_seguro_numerico',
    'Riesgo Tipo Documento (Ponderado)': 'tipo_documento_numerico',
    'Riesgo Valor Prima (Ponderado)': 'valor_prima_dolares_numerico',
    'Riesgo Contacto Físico (Ponderado)': 'frecuencia_contacto_fisico_numerico',
    'Riesgo Contacto Digital (Ponderado)': 'frecuencia_contacto_digital_numerico',
    'Riesgo Medio Comunicación (Ponderado)': 'medio_comunicacion_numerico',
    'Riesgo Medio Pago (Ponderado)': 'medio_pago_numerico',
    'Riesgo Integridad Documental (Ponderado)': 'integridad_documental_numerico',
    'Riesgo Exactitud Documental (Ponderado)': 'exactitud_documental_numerico',
    'Riesgo Vigencia Documental (Ponderado)': 'vigencia_documental_numerico',
    'Riesgo Relevancia Información (Ponderado)': 'relevancia_informacion_numerico',
    'Riesgo Consistencia Información (Ponderado)': 'consistencia_informacion_numerico',
    'Riesgo Comportamiento Cliente (Ponderado)': 'comportamiento_cliente_numerico'
  }
};

export const IMPORT_STEPS = {
  SELECT_FILE: 1,
  PREVIEW: 2,
  CONFIRM: 3
};

export const ALLOWED_FILE_TYPES = [
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-excel',
  'text/csv'
];