export const CLIENTES_INTERNOS_SCHEMA = {
  requiredFields: [
    'Nombres',
    'Nro. Documento',
    'Tipo Documento'
  ],
  fieldMappings: {
    'ID': 'id',
    'Fecha de Registro': 'fecha_registro',
    'Oficina': 'oficina',
    'Ejecutivo': 'ejecutivo',
    'Nombres': 'nombres_cliente_interno',
    'Apellidos': 'apellidos_cliente_interno',
    'Tipo Documento': 'tipo_documento_cliente_interno',
    'Nro. Documento': 'nro_documento_cliente_interno',
    'Extensión': 'extension_cliente_interno',
    'Otra Extensión': 'otra_extension_cliente_interno',
    'Fecha Nacimiento': 'fecha_nacimiento',
    'Lugar Nacimiento': 'lugar_nacimiento',
    'Nacionalidad': 'nacionalidad',
    'Estado Civil': 'estado_civil',
    'Profesión': 'profesion',
    'Riesgo Profesión/Actividad': 'riesgo_profesion_actividad',
    'Domicilio': 'domicilio_persona_sucursal',
    'Riesgo Zona': 'riesgo_zona',
    'PEP': 'categoria_pep',
    'Ingresos Mensuales': 'ingresos_mensuales',
    'Volumen Actividad': 'volumen_actividad',
    'Frecuencia Actividad': 'frecuencia_actividad',
    'Integridad Documental': 'integridad_documental',
    'Exactitud Documental': 'exactitud_documental',
    'Vigencia Documental': 'vigencia_documental',
    'Relevancia Información': 'relevancia_informacion',
    'Consistencia Información': 'consistencia_informacion',
    'Comportamiento Cliente': 'comportamiento_cliente',
    'Observaciones': 'observaciones',
    'Alertas de Clientes Internos': 'alertas_cliente_interno',
    'Alertas de Activos Virtuales': 'alertas_activos_virtuales',
    'Nacionalidad (Ponderado)': 'nacionalidad_numerico',
    'Riesgo Profesión (Ponderado)': 'riesgo_profesion_actividad_numerico',
    'Riesgo Zona (Ponderado)': 'riesgo_zona_numerico',
    'PEP (Ponderado)': 'categoria_pep_numerico',
    'Ingresos Mensuales (Ponderado)': 'ingresos_mensuales_numerico',
    'Volumen Actividad (Ponderado)': 'volumen_actividad_numerico',
    'Frecuencia Actividad (Ponderado)': 'frecuencia_actividad_numerico',
    'Integridad Documental (Ponderado)': 'integridad_documental_numerico',
    'Exactitud Documental (Ponderado)': 'exactitud_documental_numerico',
    'Vigencia Documental (Ponderado)': 'vigencia_documental_numerico',
    'Relevancia Información (Ponderado)': 'relevancia_informacion_numerico',
    'Consistencia Información (Ponderado)': 'consistencia_informacion_numerico',
    'Comportamiento Cliente (Ponderado)': 'comportamiento_cliente_numerico',
  }
};

export const ALLOWED_FILE_TYPES = [
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-excel',
  'text/csv'
];