export const COLUMNAS_REPORTE = [
    { id: 'oficina', nombre: 'Oficina' },
    { id: 'ejecutivo', nombre: 'Ejecutivo' },
    { id: 'nombres_cliente_interno', nombre: 'Nombres' },
    { id: 'apellidos_cliente_interno', nombre: 'Apellidos' },
    { id: 'tipo_documento_cliente_interno', nombre: 'Tipo Documento' },
    { id: 'nro_documento_cliente_interno', nombre: 'Nro. Documento' },
    
    { id: 'lugar_nacimiento', nombre: 'Lugar Nacimiento' },
    { id: 'nacionalidad', nombre: 'Nacionalidad' },
    { id: 'nacionalidad_numerico', nombre: 'Riesgo país' },
    { id: 'riesgo_profesion_actividad', nombre: 'Riesgo Profesión' },
    { id: 'riesgo_profesion_actividad_numerico', nombre: 'Riesgo Profesión (numérico)' },
    { id: 'riesgo_zona', nombre: 'Riesgo Zona' },
    { id: 'riesgo_zona_numerico', nombre: 'Riesgo Zona (numérico)' },
    { id: 'categoria_pep', nombre: 'Categoría PEP' },
    { id: 'categoria_pep_numerico', nombre: 'Riesgo PEP (numérico)' },
    { id: 'ingresos_mensuales', nombre: 'Ingresos Mensuales' },
    { id: 'ingresos_mensuales_numerico', nombre: 'Riesgo Ingresos (numérico)' },
    { id: 'volumen_actividad', nombre: 'Volumen Actividad' },
    { id: 'volumen_actividad_numerico', nombre: 'Riesgo Volumen (numérico)' },
    { id: 'frecuencia_actividad', nombre: 'Frecuencia Actividad' },
    { id: 'frecuencia_actividad_numerico', nombre: 'Riesgo Frecuencia (numérico)' },
    { id: 'domicilio_persona_sucursal', nombre: 'Domicilio' },
    { id: 'integridad_documental', nombre: 'Integridad Documental' },
    { id: 'integridad_documental_numerico', nombre: 'Riesgo Integridad (numérico)' },
    { id: 'exactitud_documental', nombre: 'Exactitud Documental' },
    { id: 'exactitud_documental_numerico', nombre: 'Riesgo Exactitud (numérico)' },
    { id: 'vigencia_documental', nombre: 'Vigencia Documental' },
    { id: 'vigencia_documental_numerico', nombre: 'Riesgo Vigencia (numérico)' },
    { id: 'relevancia_informacion', nombre: 'Relevancia Información' },
    { id: 'relevancia_informacion_numerico', nombre: 'Riesgo Relevancia (numérico)' },
    { id: 'consistencia_informacion', nombre: 'Consistencia Información' },
    { id: 'consistencia_informacion_numerico', nombre: 'Riesgo Consistencia (numérico)' },
    { id: 'comportamiento_cliente', nombre: 'Comportamiento' },
    { id: 'comportamiento_cliente_numerico', nombre: 'Riesgo Comportamiento (numérico)' },
    ];



export const COLUMNAS_NUMERICAS = COLUMNAS_REPORTE.filter(col => col.id.endsWith('_numerico'));